- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Lobby
  #League change
#  - Amber
#  - Bagel
#  - Box
#  - Convex
  #- Core
#  - Elkridge
#  - Fland
  #- Gate
#  - Loop
#  - Marathon
#  - Meta
#  - Oasis
#  - Omega
#  - Packed
#  - Plasma
#  - Reach
  #- Train
